Resources:
  ActorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.actorsTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  CompaniesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.companiesTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  BackgroundJobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.backgroundJobsTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
          StreamViewType: KEYS_ONLY


